FROM node:20-alpine AS build

WORKDIR /app

ENV HUSKY=0

COPY package*.json ./
COPY frontend/package*.json frontend/

RUN npm install

COPY frontend /app/frontend

WORKDIR /app/frontend

ARG VITE_API_BASE_URL=http://localhost:8000/api
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm run build

FROM nginx:1.27-alpine

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
